# A.  Arrays 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2 = np.array([1,2,3],dtype= np.float32)

In [9]:
print(arr2)

[1. 2. 3.]


In [8]:
print(repr(arr2))

array([1., 2., 3.], dtype=float32)


# B. Copying

In [10]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


# C. Casting

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr = arr.astype(np.float32)

In [13]:
arr.dtype

dtype('float32')

# Ranged data

In [14]:
arr = np.arange(10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.arange(5.1)

In [17]:
arr

array([0., 1., 2., 3., 4., 5.])

In [20]:
arr = np.arange(5.12)

In [21]:
arr

array([0., 1., 2., 3., 4., 5.])

In [22]:
arr = np.arange(-1, 4)

In [23]:
arr

array([-1,  0,  1,  2,  3])

In [24]:

arr = np.arange(-1.5, 4, 2)

In [25]:
arr

array([-1.5,  0.5,  2.5])

In [26]:
arr = np.linspace(1,5,6)

In [27]:
arr

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [33]:
arr = np.linspace(1,5,num=2,dtype=int)

In [34]:
arr

array([1, 5])

# Reshaping data

In [44]:
arr =np.arange(8)

In [42]:
arr = np.reshape(arr,(4,-1))

In [43]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [45]:
reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


# Zeros and ones

In [46]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]])


In [47]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]])
